version: 2

aliases:
  restore_npm_cache: &restore_npm_cache
    restore_cache:
      name: Restore npm cache
      keys:
        - npm-cache-{{ checksum "package.json" }}
        - npm-cache-

  persist_npm_cache: &persist_npm_cache
    save_cache:
      name: Persist npm cache
      key: npm-cache-{{ checksum "package.json" }}
      paths:
        - ../.npm

jobs:
  lint:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
    steps:
      - checkout
      - <<: *restore_npm_cache
      - run: npm ci
      - <<: *persist_npm_cache
      - run: npm run test:code-style

  zapier-validate:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
    steps:
      - checkout
      - <<: *restore_npm_cache
      - run: npm ci
      - <<: *persist_npm_cache
      - run: npm run zapier:validate

workflows:
  version: 2
  lint-build-test:
    jobs:
      - lint
      - zapier-validate
